base_url = "https://billhegazy.com/"
compile_sass = true
title = "Bill Hegazy"
description = "Blogs About Cloud, AWS, DevOps and Life"
generate_feed = true
feed_filename = "atom.xml"
theme = "abridge"
build_search_index = false
minify_html = false
taxonomies = [
    {name = "tags", feed = true}
]

[markdown]
highlight_code = true
highlight_theme = "OneHalfDark" # OneHalfDark, material-dark, ayu-dark, Midnight.dark

[extra]
katex_enable = false # used to to render mathematical notations, requires js
recent = true
recent_items = 9
footer_credit = false
#google = "Your Google Site verification code."
textlogo = '<font color="#0072b1">Bill</font> Hegazy'
sitedesc = true # This enables or disables the display of the site description below the logo.
author = "Bill Hegazy"
keywords = "Cloud, AWS, DevOps, Life, Blog, Bill, Hegazy, bhegazy, Billhegazy"
banner = "banner.png"
menu = [
    {url = "/", name = "Home", slash = true},
    {url = "/posts/", name = "Posts", slash = true},
    {url = "/tags/", name = "Tags", slash = true},
    {url = "/about/", name = "About", slash = true},
]
menu_footer = [
    {url = "/", name = "Home", slash = true},
    {url = "/about/", name = "About", slash = true},
    {url = "/privacy/", name = "Privacy", slash = true},
    {url = "/sitemap.xml", name = "Sitemap", slash = false},
]
# meta tags
twitter = "billhegazy"

favicon = "images/favicon.ico"
[extra.social]
feed = true
linkedin = "bhegazy"
github = "bhegazy"
twitter = "billhegazy"
docker = "bhegazy"
stack = "6570086"